version: "3.3"
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${YONEMO_DATABASE_USER}
      - POSTGRES_PASSWORD=${YONEMO_DATABASE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  postgres:
