default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 10 } %>
  host: <%= ENV.fetch('YONEMO_DATABASE_HOST') { '127.0.0.1' } %>
  username: <%= ENV.fetch('YONEMO_DATABASE_USER') %>
  password: <%= ENV.fetch('YONEMO_DATABASE_PASSWORD') %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: yonemo_platform_development

test:
  <<: *default
  database: yonemo_platform_test

production:
  <<: *default
  database: yonemo_platform_production

